language: node_js
sudo: false
cache: yarn
node_js:
  - "8.9.4"
install:
  - yarn install
script:
  - yarn check --integrity
  - yarn setup
  - yarn eslint
  - yarn test
  - yarn test-coverage
  - yarn test:codecov-upload
