version: '2.1'

services:
  probate-frontend:
    build:
      context: .
    image: hmctspublic/azurecr.io/probate/frontend
    container_name: probate-frontend
    environment:
      - USE_HTTPS=false
      - USE_AUTH=false
      - USE_IDAM=false
      - VALIDATION_SERVICE_URL=http://business-service:8081/validate
      - CHECK_ANSWERS_PDF_SERVICE_URL=http://business-service:8080/businessDocument/generateCheckAnswersSummaryPDF
      - http_proxy=
      - https_proxy=
      - no_proxy=
    ports:
     - 3000:3000
    links:
     - business-service
    depends_on:
     - business-service
    networks:
      default:
        aliases:
          - https://www-local.probate.reform.hmcts.net

  business-service:
    image: probate/business-service
    container_name: business-service
    environment:
      - SERVER_PORT=8081
      - http_proxy=
      - https_proxy=
      - no_proxy=
    ports:
     - 8081:8081

  idam-postfix:
    image: catatnight/postfix
    container_name: idam-postfix
    environment:
        - maildomain=localhost
        - smtp_user=localhost:Pr0bate!23
    ports:
      - 25:25
