version: '2.1'

services:
  e2e-test:
    build:
       context: ../
       dockerfile: docker/test/Dockerfile
    container_name: probate-e2e
    environment:
      - http_proxy=
      - https_proxy=
      - no_proxy=
      - TEST_USE_IDAM=true
      - TEST_E2E_FRONTEND_URL=https://localhost:3000
      - TEST_IDAM_API_URL=http://idam-api:8080
      - TEST_IDAM_LOGIN_URL=https://localhost:8000/login
      - VALIDATION_SERVICE_URL=http://business-service:8081/validate
      - SUBMIT_SERVICE_URL=http://submit-service:8181/submit
      - PERSISTENCE_SERVICE_URL=http://persistence-service:8282/formdata
    links:
      - probate-frontend
      - idam-api
      - business-service
      - submit-service
      - persistence-service
    depends_on:
      - probate-frontend
      - idam-api
      - business-service
      - submit-service
      - persistence-service
    volumes:
      - ./test/end-to-end/output:/opt/app/output

  probate-frontend:
    build:
      context: ../
    container_name: probate-frontend
    environment:
      - USE_IDAM=true
      - NODE_ENV=testing
      - VALIDATION_SERVICE_URL=http://business-service:8081/validate
      - SUBMIT_SERVICE_URL=http://submit-service:8181/submit
      - PERSISTENCE_SERVICE_URL=http://persistence-service:8282/formdata
      - IDAM_API_URL=http://idam-api:8080
      - IDAM_URL=http://idam-api:8080
      - IDAM_LOGIN_URL=https://localhost:8000/login
      - FRONTEND_HOSTNAME=localhost:3000
      - IDAM_API_OAUTH2_CLIENT_CLIENT_SECRETS_PROBATE=123456
      - http_proxy=
      - https_proxy=
      - no_proxy=
    ports:
     - 3000:3000
    links:
      - idam-api
      - authentication-web
      - business-service
      - submit-service
      - persistence-service
    depends_on:
      - idam-api
      - authentication-web
      - business-service
      - submit-service
      - persistence-service
    networks:
      default:
        aliases:
          - www-docker.probate.reform.hmcts.net

  business-service:
    image: docker.artifactory.reform.hmcts.net/probate/business-service
    container_name: business-service
    environment:
      - SERVER_PORT=8081
      - http_proxy=
      - https_proxy=
      - no_proxy=
    ports:
     - 8081:8081

  submit-service:
    image: docker.artifactory.reform.hmcts.net/probate/submit-service
    container_name: submit-service
    environment:
      - SERVER_PORT=8181
      - PROBATE_MAIL_HOST=probate-postfix
      - PROBATE_MAIL_PORT=25
      - PROBATE_MAIL_USERNAME=localhost
      - PROBATE_MAIL_PASSWORD=Pr0bate!23
      - PROBATE_MAIL_SENDER=probate-application@hmcts.net
      - PROBATE_MAIL_RECIPIENT=test.probate.inbox@gmail.com
      - PROBATE_PERSISTENCE_HOSTNAME=persistence-service:8282
      - http_proxy=
      - https_proxy=
      - no_proxy=
    ports:
     - 8181:8181
    depends_on:
      - probate-postfix

  persistence-service:
    image: docker.artifactory.reform.hmcts.net/probate/persistence-service
    command: --wait-for-database 30
    container_name: persistence-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://persistence-service-database:5432/probate
      - PROBATE_POSTGRESQL_HOSTNAME=persistence-service-database
      - PROBATE_POSTGRESQL_PORT=5432
      - PROBATE_POSTGRESQL_DATABASE=probate
      - PROBATE_POSTGRESQL_USER=probate
      - PROBATE_POSTGRESQL_PASSWORD=probate
      - PROBATE_PERSISTENCE_PORT=8282
      - http_proxy=
      - https_proxy=
      - no_proxy=
    ports:
     - 8282:8282
    depends_on:
      - persistence-service-database

  idam-api:
    image: docker.artifactory.reform.hmcts.net/auth/idam-api
    command: --wait-for-database 30
    container_name: idam-api
    environment:
      - IDAM_SUPERUSER_EMAIL
      - SPRING_DATASOURCE_URL=jdbc:postgresql://idam-database:5432/idam
      - SPRING_PROFILES_ACTIVE=test
      - IDAM_TESTING_SUPPORT_ENABLED=true
      - LOGGING_LEVEL_UK_GOV_HMCTS_IDAM=DEBUG
      - IDAM_AUTHENTICATION_WEB_HOST=https://authentication-web:8000
      - IDAM_REGISTRATION_WEB_HOST=https://www-local.registration.reform.hmcts.net:9000
      - IDAM_PROBATE_URL=https://www-local.registration.reform.hmcts.net:9000/poc/probate
      - IDAM_CMC_URL=https://www-local.registration.reform.hmcts.net:9000/poc
      - IDAM_DIVORCE_URL=https://www-local.registration.reform.hmcts.net:9000/poc/divorce
      - IDAM_SSCS_URL=https://www-local.registration.reform.hmcts.net:9000/poc
      - IDAM_CCD_URL=https://www-local.registration.reform.hmcts.net:9000/poc/ccd
      - IDAM_API_OAUTH2_CLIENT_CLIENT_SECRETS_PROBATE=123456
      - http_proxy=
      - https_proxy=
      - no_proxy=
    ports:
      - 8484:8080
    depends_on:
      - idam-database

  registration-web:
    image: docker.artifactory.reform.hmcts.net/auth/registration-web
    container_name: registration-web
    environment:
      - IDAM_API_URL=http://idam-api:8080
      - IDAM_LOGIN_URL=https://authentication-web:8000/login
    links:
      - idam-api
      - authentication-web
    ports:
      - 9000:9000
    depends_on:
      - idam-api

  authentication-web:
    image: docker.artifactory.reform.hmcts.net/auth/authentication-web
    container_name: authentication-web
    environment:
        - IDAM_API_URL=http://idam-api:8080
    ports:
      - 8000:8000
    links:
      - idam-api
    depends_on:
      - idam-api

  idam-database:
    image: docker.artifactory.reform.hmcts.net/auth/idam-database
    container_name: idam-database
    ports:
      - 5431:5432
    volumes:
      - idam-database-data:/var/lib/postgresql/data


  persistence-service-database:
    image: docker.artifactory.reform.hmcts.net/probate/persistence-service-database
    container_name: persistence-service-database
    ports:
      - 5432:5432
    volumes:
      - persistence-service-database-data:/var/lib/postgresql/data

  probate-postfix:
    image: catatnight/postfix
    container_name: probate-postfix
    environment:
        - maildomain=localhost
        - smtp_user=localhost:Pr0bate!23
    ports:
      - 25:25

volumes:
  persistence-service-database-data:
  idam-database-data:
