apiVersion: v1
description: A Helm chart for the HMCTS probate product
name: probate-frontend
home: https://github.com/hmcts/probate-frontend
version: 1.0.4
maintainers:
  - name: HMCTS Probate Team
    email: probate-action-group@HMCTS.NET
