dependencies:
  - name: rpe-feature-toggle-api
    version: ~3.2.0
    repository: '@hmctspublic'
    condition: rpe-feature-toggle-api.enabled
  - name: nodejs
    version: 1.10.0
    repository: '@hmctspublic'
  - name: redis
    version: 5.1.2
    repository: '@stable'
    condition: redis.enabled
  - name: idam-pr
    version: ~2.1.3
    repository: '@hmctspublic'
    condition: idam-pr.enabled
