
nodejs:
  memoryRequests: "512Mi"
  cpuRequests: "100m"
  memoryLimits: "1024Mi"
  cpuLimits: "500m"
  applicationPort: 3000
  memoryRequests: "512Mi"
  cpuRequests: "100m"
  memoryLimits: "1024Mi"
  cpuLimits: "500m"
  environment:
    PUBLIC_PROTOCOL: https
    REFORM_TEAM: probate
    REFORM_SERVICE_NAME: probate-frontend
    S2S_URL: http://rpe-service-auth-provider-aat.service.core-compute-aat.internal
    IDAM_S2S_AUTH_URL: http://rpe-service-auth-provider-aat.service.core-compute-aat.internal
    PAYMENT_API_URL: http://payment-api-aat.service.core-compute-aat.internal
    VALIDATION_SERVICE_URL: http://probate-business-service-aat.service.core-compute-aat.internal/validate
    BUSINESS_DOCUMENT_URL: http://probate-business-service-aat.service.core-compute-aat.internal/businessDocument
    SUBMIT_SERVICE_URL: http://probate-submit-service-aat.service.core-compute-aat.internal
    ORCHESTRATOR_SERVICE_URL : http://probate-orchestrator-service-aat.service.core-compute-aat.internal
    PERSISTENCE_SERVICE_URL: http://probate-persistence-service-aat.service.core-compute-aat.internal/formdata
    FEES_REGISTRY_URL: http://fees-register-api-aat.service.core-compute-aat.internal/fees-register
    REFORM_ENVIRONMENT : aat
    USE_REDIS : true
    REDIS_USE_TLS : false
    USE_IDAM : true
    REQUIRE_CCD_CASE_ID : true
  image: hmctspublic.azurecr.io/probate/probate-frontend:latest

redis:
  cluster:
    enabled: false
    slaveCount: 0
  usePassword: false
  master:
    persistence:
      enabled: false
