nodejs:
  applicationPort: 3000
  environment:
    PUBLIC_PROTOCOL: https
    REFORM_TEAM: probate
    REFORM_SERVICE_NAME: probate-frontend
    REFORM_ENVIRONMENT : aat
    USE_REDIS : true
    REDIS_USE_TLS : false
    REDIS_PORT : 6379
    USE_IDAM : true


  # Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}

rpe-feature-toggle-api:
  importer:
    cron:
      enabled: false
    oneoff:
      enabled: false



redis:
  cluster:
    enabled: false
    slaveCount: 0
  usePassword: false
  master:
    persistence:
      enabled: false