nodejs:
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  environment:
    REDIS_HOST: ${SERVICE_NAME}-redis-master
    REDIS_PORT: 6379
    REDIS_USE_TLS: false
    LAUNCHDARKLY_ENABLED: true
    VALIDATION_SERVICE_URL: http://probate-business-service-pr-444.service.core-compute-preview.internal/validate
    ORCHESTRATOR_SERVICE_URL: http://probate-orchestrator-service-pr-408.service.core-compute-preview.internal
  keyVaults:
    probate:
      resourceGroup: probate
      secrets:
        - idam-s2s-secret
        - ccidam-idam-api-secrets-probate
        - postcode-service-url
        - postcode-service-token2
        - probate-survey
        - probate-survey-end
        - probate-service-id
        - probate-site-id
        - probate-webchat-id
        - probate-webchat-tenant
        - probate-webchat-button-no-agents
        - probate-webchat-button-busy
        - probate-webchat-button-service-closed
        - payCaseWorkerUser
        - payCaseWorkerPass
        - launchdarkly-key
redis:
  enabled: true
idam-pr:
  enabled: true
  redirect_uris:
    Probate:
      - https://${SERVICE_FQDN}/oauth2/callback
