environment: 'prod'
nodeEnvironment: 'production'
gitRevision: ''
frontendPublicHttpProtocol: http
languages: ['en', 'cy']
featureToggles:
  enabled: true
  launchDarklyKey: 'LAUNDARKLEY-KEY'
  launchDarklyUser:
    firstName: 'Probate'
    lastName: 'Frontend'
    key: 'LAUNCHDARKLY_USER_KEY'
  ft_fees_api: 'probate-fees-api'
  ft_pcq: 'probate-pcq'
  ft_pcq_token: 'probate-pcq-token'
  ft_avaya_webchat: 'probate-avaya-webchat'
  ft_newfee_register_code: 'probate-newfee-register-code'
  ft_excepted_estates: 'probate-excepted-estates'
  ft_will_condition : 'probate-will-condition'
  ft_stop_ihtonline : 'probate-stop-ihtonline'
  ft_use_new_webchat : 'probate-use-new-webchat'
  appwideToggles: ['ft_avaya_webchat', 'ft_use_new_webchat']
# overrides featureToggles to e.g. switch off in pipeline/locally
configFeatureToggles:
  webchatEnabled: true
  gaEnabled: true
app:
  username:
  password:
  useIDAM: 'false'
  requireCcdCaseId: 'false'
  port: '3000'
  useCSRFProtection: 'true' # TODO: tech debt, tests should be csrf aware, it shouldn't be possible to accidentally disable this
  session:
    expires: 3600000 # ms (60 minutes)
    ttl: 28800 # ms (8 hours)
health:
  service_name: 'Apply for Probate'
  timeout: 30000
  deadline: 30000
services:
  postcode:
    name: 'Postcode Lookup Service'
    token:
  orchestrator:
    name: 'Orchestrator Service'
    url: 'http://localhost:8888'
    paths:
      forms: '/forms/case/{ccdCaseId}'
      create: '/forms/newcase'
      submissions: '/forms/{ccdCaseId}/submissions'
      payments: '/forms/{ccdCaseId}/payments'
      payment_updates: '/payment-updates'
      payment_submissions: '/forms/{ccdCaseId}/payment-submissions'
      fees: '/forms/{ccdCaseId}/fees'
      validations: '/forms/{ccdCaseId}/validations'
      applications: '/forms/cases'
      declarationStatuses: '/invites/{ccdCaseId}'
    port: 8888
    gitCommitIdPath: 'git.commit.id'
  validation:
    name: 'Business Service'
    url: 'http://localhost:8081/validate'
    gitCommitIdPath: 'git.commit.id'
  idam:
    name: 'IdAM Service'
    loginUrl: 'http://localhost:3501/login'
    apiUrl: 'http://localhost:5000'
    roles: ['probate-private-beta', 'citizen']
    s2s_url: 'http://localhost:4502'
    service_name: 'probate_frontend'
    service_key: 'AAAAAAAAAAAAAAAA'
    probate_oauth2_client: 'ccd_gateway'
    probate_oauth2_secret: 'ccd_gateway_secret'
    probate_oauth_callback_path: '/oauth2/callback'
    probate_oauth_token_path: '/oauth2/token'
    probate_oauth_authorise_path: '/oauth2/authorize'
    probate_user_email: 'dummy-user-name'
    probate_user_password: 'dummy-password'
    probate_redirect_base_url: 'http://localhost:3000'
  payment:
    name: 'Payment Service'
    url: 'http://localhost:8383'
    externalUrl: 'https://card.payments.service.gov.uk'
    authorization: 'DUMMY_TOKEN'
    serviceAuthorization: 'DUMMY_TOKEN'
    userId: 46
    paths:
      payments: '/payments'
      createPayment: '/card-payments'
      returnUrlPath: '/payment-status'
  pact:
    name: 'PACT Service'
    url: 'https://pact-broker.platform.hmcts.net'
    tag: 'Dev'
    pactDirectory: 'pacts'
  feesRegister:
    name: 'Fees Register Service'
    url: 'http://localhost:4411/fees-register'
    port: 4411
    paths:
      fees: '/fees'
      feesLookup: '/fees/lookup'
    ihtMinAmt: 5000
    issuesData:
      amount_or_volume: 0
      applicant_type: 'all'
      channel: 'default'
      event: 'issue'
      jurisdiction1: 'family'
      jurisdiction2: 'probate registry'
      service: 'probate'
    copiesData:
      amount_or_volume: 0
      applicant_type: 'all'
      channel: 'default'
      event: 'copies'
      jurisdiction1: 'family'
      jurisdiction2: 'probate registry'
      service: 'probate'
      keyword: 'NewFee'
    newfee_issuesData:
      amount_or_volume: 0
      applicant_type: 'all'
      channel: 'default'
      event: 'issue'
      jurisdiction1: 'family'
      jurisdiction2: 'probate registry'
      service: 'probate'
      keyword: 'SA'
    newfee_issuesDataIhtMinAmount:
      amount_or_volume: 0
      applicant_type: 'all'
      channel: 'default'
      event: 'issue'
      jurisdiction1: 'family'
      jurisdiction2: 'probate registry'
      service: 'probate'
      keyword: 'SAL5K'
    newfee_copiesData:
      amount_or_volume: 0
      applicant_type: 'all'
      channel: 'default'
      event: 'copies'
      jurisdiction1: 'family'
      jurisdiction2: 'probate registry'
      service: 'probate'
      keyword: 'GrantWill'
  equalityAndDiversity:
    name: 'Equality and Diversity Service'
    url: 'http://localhost:4000'
    path: '/service-endpoint'
    gitCommitIdPath: 'buildInfo.extra.gitCommitId'
    port: 4000
    tokenKey: 'PROBATE_TOKEN_KEY'
redis:
  host: 'localhost'
  port: 6379
  password: 'dummy_password'
  useTLS: 'false'
  enabled: 'false'
  secret: 'OVERWRITE_THIS'
  resave: false
  saveUninitialized: true
  cookie:
    httpOnly: true
    secure: true
  eligibilityCookie:
    name: '__eligibility'
    redirectUrl: '/start-eligibility'
    expires: 172800000 # 48 hours
dateFormat: 'DD/MM/YYYY'
payloadVersion: '4.1.1'
enableTracking: 'true'
webchat:
  avayaUrl: 'webchat.pp.ctsc.hmcts.net'
  avayaClientUrl: 'webchat-client.pp.ctsc.hmcts.net'
  avayaService: 'Testing'
  kerv:
    deploymentId:
      en: 'kerv-deployment-en'
      cy: 'kerv-deployment-cy'
    genesysBaseUrl: 'kerv-genesys-base-url'
    environment: 'kerv-environment'
    kervBaseUrl: 'kerv-kerv-base-url'
    apiKey: 'kerv-api-key'
links:
  accessibility: '/accessibility-statement'
  cookies: '/cookies'
  privacy: '/privacy-policy'
  terms: '/terms-conditions'
  contact: '/contact-us'
  webchat: '/avaya-webchat'
  callCharges: 'https://www.gov.uk/call-charges'
  howToManageCookies: 'https://www.aboutcookies.org'
  googlePrivacyPolicy: 'https://www.google.com/policies/privacy/partners/'
  googleAnalyticsOptOut: 'https://tools.google.com/dlpage/gaoptout/'
  mojPersonalInformationCharter: 'https://www.gov.uk/government/organisations/ministry-of-justice/about/personal-information-charter'
  goodThingsFoundation: 'https://www.goodthingsfoundation.org'
  subjectAccessRequest: 'https://www.gov.uk/government/publications/request-your-personal-data-from-moj'
  complaintsProcedure: 'https://www.gov.uk/government/organisations/hm-courts-and-tribunals-service/about/complaints-procedure'
  informationCommissionersOffice: 'https://ico.org.uk/global/contact-us'
  survey: 'https://www.smartsurvey.co.uk/s/Probate_Feedback/'
  surveyEndOfApplication: 'https://www.smartsurvey.co.uk/s/SurveyExit/?service=Probate'
  ihtNotCompleted: 'https://www.gov.uk/valuing-estate-of-someone-who-died/tell-hmrc-estate-value'
  applicationFormPA14: 'https://www.gov.uk/government/publications/form-pa14-medical-certificate-probate'
  applicationFormPA17: 'https://www.gov.uk/government/publications/form-pa17-give-up-probate-executor-rights-for-probate-practitioners'
  applicationFormPA15: 'https://www.gov.uk/government/publications/form-pa15-give-up-probate-executor-rights'
  applicationFormPA1A: 'https://www.gov.uk/government/publications/form-pa1a-apply-for-probate-deceased-did-not-leave-a-will'
  applicationFormPA1P: 'https://www.gov.uk/government/publications/form-pa1p-apply-for-probate-the-deceased-had-a-will'
  applicationFormPA19: 'https://www.gov.uk/government/publications/form-pa19-apply-for-a-grant-of-representation-with-a-foreign-death-certificate-not-translated-by-a-licensed-company'
  deathCertificate: 'https://www.gov.uk/order-copy-birth-death-marriage-certificate'
  hmctAccessAccessibilityStatement: 'https://hmcts-access.service.gov.uk/accessibility-statement'
  payAccessibilityStatement: 'https://www.payments.service.gov.uk/accessibility-statement/'
  notifyAccessibilityStatement: 'https://www.notifications.service.gov.uk/accessibility-statement'
  deathReportedToCoroner: 'https://www.gov.uk/after-a-death/when-a-death-is-reported-to-a-coroner'
  findOutNext: 'https://www.gov.uk/wills-probate-inheritance/once-the-grants-been-issued'
  whoInherits: 'https://www.gov.uk/inherits-someone-dies-without-will'
  ifYoureAnExecutor: 'https://www.gov.uk/wills-probate-inheritance/if-youre-an-executor'
  renunciationForm: 'https://www.gov.uk/government/publications/form-pa15-apply-for-renunciation-will'
  assessingMentalCapacity: 'https://www.gov.uk/make-decisions-for-someone/assessing-mental-capacity'
  myAbilityLink: 'https://mcmw.abilitynet.org.uk/'
  equalityAdvisorLink: 'https://www.equalityadvisoryservice.com/'
  wcag21Link: 'https://www.w3.org/TR/WCAG21/'
  ihtChecker: 'https://www.gov.uk/valuing-estate-of-someone-who-died/estimate-estate-value'
  ihtTaxChecker: 'https://www.gov.uk/valuing-estate-of-someone-who-died/estimate-estate-value#use-the-online-inheritance-tax-checker'
  ihtThreshold: 'https://www.gov.uk/inheritance-tax'
  ihtTransferOfThreshold: 'https://www.gov.uk/guidance/inheritance-tax-transfer-of-threshold'
  ihtNoInheritanceTax: 'https://www.gov.uk/valuing-estate-of-someone-who-died/check-type-of-estate'
  ihtGifts: 'https://www.gov.uk/inheritance-tax/gifts'
  spouseGivingUpAdminRightsPA16Link: 'https://www.gov.uk/government/publications/form-pa16-give-up-probate-administrator-rights'
  willIsLegal: 'https://www.gov.uk/make-will/make-sure-your-will-is-legal'
  solicitorsRegulationAuthority: 'https://www.sra.org.uk'
  findOriginalWill: 'https://www.gov.uk/applying-for-probate/if-theres-a-will#find-the-original-will'
  applyForProbateFrontpage: 'https://www.apply-for-probate.service.gov.uk/start-eligibility'
  applyForProbateFrontpageWelsh: 'https://www.gov.uk/gwneud-cais-am-brofiant/gwneud-cais-am-brofiant'
  paymentsAccessibilityStatement: 'https://www.payments.service.gov.uk/accessibility-statement/'
utils:
  api:
    retries: 10
    retryDelay: 1000
payment:
  serviceId: 'PROBATE'
  siteId: 'P223'
  version: '1'
  currency: 'GBP'
noHeaderLinksPages: ['/time-out', '/sign-out', '/co-applicant-start-page', '/co-applicant-declaration', '/co-applicant-agree-page', '/co-applicant-disagree-page', '/co-applicant-all-agreed-page', '/pin-resend', '/pin-sent', '/sign-in']
alwaysWhitelistedPages: ['/time-out', '/sign-out', '/contact-us', '/accessibility-statement', '/terms-conditions', '/privacy-policy', '/cookies', '/health', '/stop-page', '/error', '/avaya-webchat']
whitelistedPagesAfterSubmission: ['/documents', '/thank-you', '/check-answers-pdf', '/declaration-pdf', '/citizens-hub']
whitelistedPagesAfterPayment: ['/payment-status', '/documents', '/thank-you', '/check-answers-pdf', '/declaration-pdf']
whitelistedPagesAfterDeclaration: ['/task-list', '/executors-invites-sent', '/copies-uk', '/assets-overseas', '/copies-overseas', '/copies-summary', '/payment-breakdown', '/payment-status', '/documents', '/thank-you', '/check-answers-pdf', '/declaration-pdf', '/equality-and-diversity', '/citizens-hub']
blacklistedPagesBeforeDeclaration: ['/executors-invites-sent', '/copies-uk', '/assets-overseas', '/copies-overseas', '/copies-summary', '/payment-breakdown', '/payment-status', '/documents', '/thank-you', '/check-answers-pdf', '/declaration-pdf', '/citizens-hub']
probateScreenersDeathCertificateInEnglish:
  deathCertificate: 'optionYes'
  deathCertificateInEnglish: 'optionYes'
  domicile: 'optionYes'
  completed: 'optionYes'
  left: 'optionYes'
  original: 'optionYes'
  executor: 'optionYes'
  mentalCapacity: 'optionYes'
probateScreenersDeathCertificateNotInEnglish:
  deathCertificate: 'optionYes'
  deathCertificateInEnglish: 'optionNo'
  deathCertificateTranslation: 'optionYes'
  domicile: 'optionYes'
  completed: 'optionYes'
  left: 'optionYes'
  original: 'optionYes'
  executor: 'optionYes'
  mentalCapacity: 'optionYes'
probateScreenersDeathCertificateInEnglishExceptedEstates:
  deathCertificate: 'optionYes'
  deathCertificateInEnglish: 'optionYes'
  domicile: 'optionYes'
  eeDeceasedDod: 'optionYes'
  eeEstateValued: 'optionYes'
  left: 'optionYes'
  original: 'optionYes'
  executor: 'optionYes'
  mentalCapacity: 'optionYes'
probateScreenersDeathCertificateNotInEnglishExceptedEstates:
  deathCertificate: 'optionYes'
  deathCertificateInEnglish: 'optionNo'
  deathCertificateTranslation: 'optionYes'
  domicile: 'optionYes'
  eeDeceasedDod: 'optionYes'
  eeEstateValued: 'optionYes'
  left: 'optionYes'
  original: 'optionYes'
  executor: 'optionYes'
  mentalCapacity: 'optionYes'
probateScreenersDeathCertificateInEnglishDodBeforeThresholdExceptedEstates:
  deathCertificate: 'optionYes'
  deathCertificateInEnglish: 'optionYes'
  domicile: 'optionYes'
  eeDeceasedDod: 'optionNo'
  completed: 'optionYes'
  left: 'optionYes'
  original: 'optionYes'
  executor: 'optionYes'
  mentalCapacity: 'optionYes'
probateScreenersDeathCertificateNotInEnglishDodBeforeThresholdExceptedEstates:
  deathCertificate: 'optionYes'
  deathCertificateInEnglish: 'optionNo'
  deathCertificateTranslation: 'optionYes'
  domicile: 'optionYes'
  eeDeceasedDod: 'optionNo'
  completed: 'optionYes'
  left: 'optionYes'
  original: 'optionYes'
  executor: 'optionYes'
  mentalCapacity: 'optionYes'
intestacyScreenersDeathCertificateInEnglish:
  deathCertificate: 'optionYes'
  deathCertificateInEnglish: 'optionYes'
  domicile: 'optionYes'
  completed: 'optionYes'
  left: 'optionNo'
  diedAfter: 'optionYes'
  related: 'optionYes'
  otherApplicants: 'optionNo'
intestacyScreenersDeathCertificateNotInEnglish:
  deathCertificate: 'optionYes'
  deathCertificateInEnglish: 'optionNo'
  deathCertificateTranslation: 'optionYes'
  domicile: 'optionYes'
  completed: 'optionYes'
  left: 'optionNo'
  related: 'optionYes'
  otherApplicants: 'optionNo'
intestacyScreenersDeathCertificateInEnglishExceptedEstates:
  deathCertificate: 'optionYes'
  deathCertificateInEnglish: 'optionYes'
  domicile: 'optionYes'
  eeDeceasedDod: 'optionYes'
  eeEstateValued: 'optionYes'
  left: 'optionNo'
  related: 'optionYes'
  otherApplicants: 'optionNo'
intestacyScreenersDeathCertificateNotInEnglishExceptedEstates:
  deathCertificate: 'optionYes'
  deathCertificateInEnglish: 'optionNo'
  deathCertificateTranslation: 'optionYes'
  domicile: 'optionYes'
  eeDeceasedDod: 'optionYes'
  eeEstateValued: 'optionYes'
  left: 'optionNo'
  related: 'optionYes'
  otherApplicants: 'optionNo'
intestacyScreenersDeathCertificateInEnglishDodBeforeThresholdExceptedEstates:
  deathCertificate: 'optionYes'
  deathCertificateInEnglish: 'optionYes'
  domicile: 'optionYes'
  eeDeceasedDod: 'optionNo'
  completed: 'optionYes'
  left: 'optionNo'
  diedAfter: 'optionYes'
  related: 'optionYes'
  otherApplicants: 'optionNo'
intestacyScreenersDeathCertificateNotInEnglishDodBeforeThresholdExceptedEstates:
  deathCertificate: 'optionYes'
  deathCertificateInEnglish: 'optionNo'
  deathCertificateTranslation: 'optionYes'
  domicile: 'optionYes'
  eeDeceasedDod: 'optionNo'
  completed: 'optionYes'
  left: 'optionNo'
  diedAfter: 'optionYes'
  related: 'optionYes'
  otherApplicants: 'optionNo'
hardStopParams:
  gop: []
  intestacy: []
nonIdamPages: ['health/*', 'stop-page/*', 'error', 'sign-in', 'pin-resend', 'pin-sent', 'co-applicant-*', 'pin', 'inviteIdList', 'start-eligibility', 'death-certificate', 'death-certificate-english', 'death-certificate-translation', 'deceased-domicile', 'iht-completed', 'will-left', 'will-original', 'applicant-executor', 'mental-capacity', 'died-after-october-2014', 'related-to-deceased', 'other-applicants', 'start-apply', 'contact-us', 'accessibility-statement', 'terms-conditions', 'privacy-policy', 'cookies', 'avaya-webchat', 'ee-deceased-dod', 'ee-estate-valued', 'time-out']
noCcdCaseIdPages: ['health/*', 'stop-page/*', 'error', 'sign-in', 'pin-resend', 'pin-sent', 'co-applicant-*', 'pin', 'inviteIdList', 'start-eligibility', 'death-certificate','death-certificate-english', 'death-certificate-translation', 'deceased-domicile', 'iht-completed', 'will-left', 'will-original', 'applicant-executor', 'mental-capacity', 'died-after-october-2014', 'related-to-deceased', 'other-applicants', 'start-apply', 'contact-us', 'accessibility-statement', 'terms-conditions', 'privacy-policy', 'cookies', 'dashboard', 'sign-out', 'time-out', 'avaya-webchat', 'ee-deceased-dod', 'ee-estate-valued', 'task-list']
endpoints:
  health: '/health'
  info: '/info'
appInsights:
  connectionString:
documentUpload:
  validMimeTypes: ['image/jpeg', 'image/bmp', 'image/tiff', 'image/png', 'application/pdf']
  maxFiles: 10
  maxSizeBytes: 10485760 # 10 MB
  maxSizeBytesTest: 10240 # 10 KB
  paths:
    upload: '/documents/upload'
    remove: '/documents/delete'
  error:
    invalidFileType: 'Error: invalid file type'
    maxSize: 'Error: invalid file size'
    maxFiles: 'Error: too many files'
    nothingUploaded: 'Error: no files passed'
    uploadFailed: 'Error: upload failed'
    uploadTimeout: 'Error: upload timed out'
  timeoutMs: 300000
pdf:
  template:
    checkAnswers: 'checkAnswersSummary'
    declaration: 'legalDeclaration'
    coverSheet: 'bulkScanCoversheet'
  path: '/documents/generate'
  timeoutMs: 30000
assetsValueThreshold: [
  {
    minDate: '2014-10-01',
    maxDate: '2020-02-05',
    value: 250000
  },
  {
    minDate: '2020-02-06',
    value: 270000
  }
]
exceptedEstateDateOfDeath: '2022-01-01'
estateQualifyingValueRange:
  min: 325000
  max: 650000
eventDescriptionPrefix: 'Page completed: '
dynatrace:
  dynatraceUrl: 'https://js-cdn.dynatrace.com/jstag/17177a07246/bf24054dsx/27a3075f1661d271_complete.js'
disposal:
  switchDate: '2025-03-04'
  inactivityDaysThreshold: 90
  deletionDaysThreshold: 90
