# Use for testing http - e.g. local env
environment: 'sandbox'

#this feature toggle shouldnt be here remove this later when not longer working end to end on local: todo remove this
featureToggles:
  enabled: true
  launchDarklyKey: 'Dummy_LD_Key'
  launchDarklyUser:
    firstName: 'Probate'
    lastName: 'Frontend'
    key: 'Dummy_User_Key'

configFeatureToggles:
  webchatEnabled: false
  gaEnabled: false

TestCitizenDomain: '/@probateTest.com'
TestDocumentToUpload: 'uploadDocuments/test_file_for_document_upload.png'
TestE2EFrontendUrl: 'http://localhost:3000'
TestFrontendUrl: 'http://localhost:3000'
TestIdamAddUserUrl: '/testing-support/accounts'
TestIdamBaseUrl: 'http://localhost:5000'
TestIdamLoginUrl: 'http://localhost:3501/login'
TestIdamRole: 'citizen'
TestIdamUserGroup: 'caseworker'
TestOutputDir: './functional-output'
TestPathToRun: './paths/**/*.js'
TestProxy: 'socks5:proxyout.reform.hmcts.net:8080'
TestRetryFeatures: 2
TestRetryScenarios: 2
TestRetrySteps: 2
TestShowBrowser: true
TestUseGovPay: 'true'
TestUseIdam: 'true'
TestUseProxy: 'false'
TestWaitForDocumentUpload: 60
TestWaitForTextToAppear: 120
TestWaitForElementToAppear: 60
TestOneMilliSecond: 1000
TestEnvEmailAddress: 'test.probate.inbox@gmail.com'
TestEnvMobileNumber: '07765453421'
TestInviteIdListUrl: '/inviteIdList'
TestInvitationUrl: '/executors/invitation'

app:
 useIDAM: 'true'

postcodeLookup:
  contentType: 'application/json'
  singleAddressPostcode: 'SW1A 1AA'
  singleOrganisationName: 'BUCKINGHAM PALACE'
  singleFormattedAddress: 'BUCKINGHAM PALACE, LONDON, SW1A 1AA'
  multipleAddressPostcode: 'N145JY'
  partialAddressPostcode: 'N14'
  invalidAddressPostcode: 'Z99 9ZZ'
  emptyAddressPostcode: ''

govPayTestCardNos:
  validCardNo: '4242424242424242'

govPayTestCardDetails:
  expiryMonth: '06'
  expiryYear: '99'
  cardholderName: 'Test Payment'
  cvc: '123'
  addressLine1: '1'
  addressCity: 'London'
  addressPostcode: 'SW1A1AA'

validation:
  url: 'http://localhost:8081/validate'

TestGovUkConfirmPaymentUrl: 'www.payments.service.gov.uk'
TestGovUkCardPaymentsUrl: '/card_details'

s2sStubErrorSequence: '000'
links:
  cookies: '/cookies'
  privacy: '/privacy-policy'
  contact: '/contact-us'
  callCharges: 'https://www.gov.uk/call-charges'
  howToManageCookies: 'https://www.aboutcookies.org'
  googlePrivacyPolicy: 'https://www.google.com/policies/privacy/partners/'
  googleAnalyticsOptOut: 'https://tools.google.com/dlpage/gaoptout/'
  mojPersonalInformationCharter: 'https://www.gov.uk/government/organisations/ministry-of-justice/about/personal-information-charter'
  goodThingsFoundation: 'https://www.goodthingsfoundation.org'
  subjectAccessRequest: 'https://www.gov.uk/government/publications/request-your-personal-data-from-moj'
  complaintsProcedure: 'https://www.gov.uk/government/organisations/hm-courts-and-tribunals-service/about/complaints-procedure'
  informationCommissionersOffice: 'https://ico.org.uk/global/contact-us'
  ihtNotCompleted: 'https://www.gov.uk/valuing-estate-of-someone-who-died/tell-hmrc-estate-value'
  applicationFormPA15: 'https://www.gov.uk/government/publications/form-pa15-apply-for-renunciation-will'

pact:
  pactBrokerUrl: 'http://localhost:80'
