featureToggles:
  enabled: false

configFeatureToggles:
  webchatEnabled: true
  gaEnabled: true

environment: local

services:
  orchestrator:
    url: ''
  payment:
    url: ''
  equalityAndDiversity:
    url: ''
