featureToggles:
  enabled: true
  launchDarklyKey: 'sdk-4d50eb6e-8400-4aa7-b4c5-8bdfc8b1d844'
  launchDarklyUser:
      firstName: 'Megan',
      lastName: 'Slattery',
      key: 'megan.slattery@hmcts.net'
      ft_new_deathcert_flow: 'probate-new-deathcert-flow'