# Use for testing https - e.g. AAT
environment: 'sandbox'

TestCitizenDomain: '/@probateTest.com'
TestDocumentToUpload: 'uploadDocuments/test_file_for_document_upload.png'
TestE2EFrontendUrl: 'https://localhost:3000'
TestFrontendUrl: 'https://localhost:3000'
TestIdamAddUserUrl: '/testing-support/accounts'
TestIdamBaseUrl: 'http://localhost:5000'
TestIdamLoginUrl: 'https://localhost:3501/login'
TestIdamRole: 'citizen'
TestIdamUserGroup: 'caseworker'
TestOutputDir: './functional-output'
TestPathToRun: './paths/**/*.js'
TestProxy: 'socks5:proxyout.reform.hmcts.net:8080'
TestRetryFeatures: 4
TestRetryScenarios: 4
TestRetrySteps: 4
TestShowBrowser: true
TestUseGovPay: 'true'
TestUseIdam: 'true'
TestUseProxy: 'true'
TestWaitForDocumentUpload: 60
TestWaitForTextToAppear: 60
TestWaitForElementToAppear: 60
TestOneMilliSecond: 1000
TestEnvEmailAddress: 'test.probate.inbox@gmail.com'
TestEnvMobileNumber: '07765453421'
TestInviteIdListUrl: '/inviteIdList'
TestInvitationUrl: '/executors/invitation'

app:
 useIDAM: 'true'

postcodeLookup:
  contentType: 'application/json'
  singleAddressPostcode: 'SW1A 1AA'
  singleOrganisationName: 'BUCKINGHAM PALACE'
  singleFormattedAddress: 'BUCKINGHAM PALACE, LONDON, SW1A 1AA'
  multipleAddressPostcode: 'N145JY'
  partialAddressPostcode: 'N14'
  invalidAddressPostcode: 'Z99 9ZZ'
  emptyAddressPostcode: ''

featureToggles:
  enabled: false

govPayTestCardNos:
  validCardNo: '4242424242424242'

govPayTestCardDetails:
  expiryMonth: '06'
  expiryYear: '99'
  cardholderName: 'Test Payment'
  cvc: '123'
  addressLine1: '1'
  addressCity: 'London'
  addressPostcode: 'SW1A1AA'

validation:
  url: 'http://localhost:8081/validate'

TestGovUkConfirmPaymentUrl: 'www.payments.service.gov.uk'
TestGovUkCardPaymentsUrl: '/card_details'

s2sStubErrorSequence: '000'
links:
  cookies: '/cookies'
  privacy: '/privacy-policy'
  contact: '/contact-us'
  callCharges: 'https://www.gov.uk/call-charges'
  howToManageCookies: 'https://www.aboutcookies.org'
  googlePrivacyPolicy: 'https://www.google.com/policies/privacy/partners/'
  googleAnalyticsOptOut: 'https://tools.google.com/dlpage/gaoptout/'
  mojPersonalInformationCharter: 'https://www.gov.uk/government/organisations/ministry-of-justice/about/personal-information-charter'
  goodThingsFoundation: 'https://www.goodthingsfoundation.org'
  subjectAccessRequest: 'https://www.gov.uk/government/publications/request-your-personal-data-from-moj'
  complaintsProcedure: 'https://www.gov.uk/government/organisations/hm-courts-and-tribunals-service/about/complaints-procedure'
  informationCommissionersOffice: 'https://ico.org.uk/global/contact-us'
  ihtNotCompleted: 'https://www.gov.uk/valuing-estate-of-someone-who-died/tell-hmrc-estate-value'
  applicationFormPA15: 'https://www.gov.uk/government/publications/form-pa15-apply-for-renunciation-will'

helpline:
  number: '0300 303 0648'
  hours: 'Monday to Friday, 8:00am to 6:00pm. Saturday, 8:00am to 2:00pm.'

pact:
  pactBrokerUrl: 'http://localhost:80'

services:
  orchestrator:
    url: ''
  validation:
    name: 'Business Service'
    url: 'http://localhost:8081/validate'
    gitCommitIdPath: 'git.commit.id'
  idam:
    name: 'IdAM Service'
    loginUrl: 'http://localhost:3501/login'
    apiUrl: 'http://localhost:5000'
    roles: ['probate-private-beta', 'citizen']
    s2s_url: 'http://localhost:4502'
    service_name: 'probate_frontend'
    service_key: 'AAAAAAAAAAAAAAAA'
    probate_oauth2_client: 'ccd_gateway'
    probate_oauth2_secret: 'ccd_gateway_secret'
    probate_oauth_callback_path: '/oauth2/callback'
    probate_oauth_token_path: '/oauth2/token'
    probate_user_email: 'dummy-user-name'
    probate_user_password: 'dummy-password'
    probate_redirect_base_url: 'http://localhost:3000'
  payment:
    url: ''
  pact:
    name: 'PACT Service'
    url: 'http://localhost:80'
    tag: 'Dev'
    pactDirectory: 'pacts'
  feesRegister:
    name: 'Fees Register Service'
    url: 'http://localhost:4411/fees-register'
    port: 4411
    paths:
      fees: '/fees'
      feesLookup: '/fees/lookup'
    ihtMinAmt: 5000
    issuesData:
      amount_or_volume: 0
      applicant_type: 'all'
      channel: 'default'
      event: 'issue'
      jurisdiction1: 'family'
      jurisdiction2: 'probate registry'
      service: 'probate'
    copiesData:
      amount_or_volume: 0
      applicant_type: 'all'
      channel: 'default'
      event: 'copies'
      jurisdiction1: 'family'
      jurisdiction2: 'probate registry'
      service: 'probate'
      keyword: 'NewFee'
    newfee_issuesData:
      amount_or_volume: 0
      applicant_type: 'all'
      channel: 'default'
      event: 'issue'
      jurisdiction1: 'family'
      jurisdiction2: 'probate registry'
      service: 'probate'
      keyword: 'SA'
    newfee_issuesDataIhtMinAmount:
      amount_or_volume: 0
      applicant_type: 'all'
      channel: 'default'
      event: 'issue'
      jurisdiction1: 'family'
      jurisdiction2: 'probate registry'
      service: 'probate'
      keyword: 'SAL5K'
    newfee_copiesData:
      amount_or_volume: 0
      applicant_type: 'all'
      channel: 'default'
      event: 'copies'
      jurisdiction1: 'family'
      jurisdiction2: 'probate registry'
      service: 'probate'
      keyword: 'GrantWill'
  equalityAndDiversity:
    url: ''
