TestCitizenDomain: '/@probateTest.com'
TestDocumentToUpload: 'uploadDocuments/test_file_for_document_upload.png'
TestE2EFrontendUrl: 'http://localhost:3000'
TestFrontendUrl: 'http://localhost:3000'
TestIdamBaseUrl: 'http://localhost:8484'
TestIdamLoginUrl: 'https://localhost:8000/login'
TestOutputDir: './functional-output'
TestPathToRun: './paths/**/*.js'
TestProxy: 'socks5:proxyout.reform.hmcts.net:8080'
TestRetryFeatures: 4
TestRetryScenarios: 4
TestRetrySteps: 4
TestShowBrowser: false
TestUseGovPay: 'true'
TestUseIdam: 'true'
TestUseProxy: 'false'
TestWaitForDocumentUpload: 60
TestWaitForTextToAppear: 120
TestWaitForElementToAppear: 60
TestOneMilliSecond: 1000

postcodeLookup:
  contentType: 'application/json'
  singleAddressPostcode: 'SW1A 1AA'
  singleOrganisationName: 'BUCKINGHAM PALACE'
  singleFormattedAddress: 'BUCKINGHAM PALACE, LONDON, SW1A 1AA'
  multipleAddressPostcode: 'N145JY'
  partialAddressPostcode: 'N14'
  invalidAddressPostcode: 'Z99 9ZZ'
  emptyAddressPostcode: ''

govPayTestCardNos:
  validCardNo: '4242424242424242'

govPayTestCardDetails:
  expiryMonth: '06'
  expiryYear: '99'
  cardholderName: 'Test Payment'
  cvc: '123'
  addressLine1: '1'
  addressCity: 'London'
  addressPostcode: 'SW1A1AA'

TestGovUkConfirmPaymentUrl: 'www.payments.service.gov.uk'
TestGovUkCardPaymentsUrl: '/card_details'

s2sStubErrorSequence: '000'

pact:
  pactBrokerUrl: 'http://localhost:80'

featureToggles:
  enabled: false

environment: local
