# Use for testing https - e.g. AAT
environment: 'sandbox'

TestCitizenDomain: '/@probateTest.com'
TestDocumentToUpload: 'uploadDocuments/test_file_for_document_upload.png'
TestE2EFrontendUrl: 'https://localhost:3000'
TestFrontendUrl: 'https://localhost:3000'
TestIdamAddUserUrl: '/testing-support/accounts'
TestIdamBaseUrl: 'http://localhost:5000'
TestIdamLoginUrl: 'https://localhost:3501/login'
TestIdamRole: 'citizen'
TestIdamUserGroup: 'caseworker'
TestOutputDir: './functional-output'
TestPathToRun: './paths/**/*.js'
TestProxy: 'socks5:proxyout.reform.hmcts.net:8080'
TestRetryFeatures: 4
TestRetryScenarios: 4
TestRetrySteps: 4
TestShowBrowser: true
TestUseGovPay: 'true'
TestUseIdam: 'true'
TestUseProxy: 'true'
TestWaitForDocumentUpload: 60
TestWaitForTextToAppear: 60
TestWaitForElementToAppear: 60
TestOneMilliSecond: 1000
TestEnvEmailAddress: 'test.probate.inbox@gmail.com'
TestEnvMobileNumber: '07765453421'
TestInviteIdListUrl: '/inviteIdList'
TestInvitationUrl: '/executors/invitation'

postcodeLookup:
  contentType: 'application/json'
  singleAddressPostcode: 'SW1A 1AA'
  singleOrganisationName: 'BUCKINGHAM PALACE'
  singleFormattedAddress: 'BUCKINGHAM PALACE, LONDON, SW1A 1AA'
  multipleAddressPostcode: 'N145JY'
  partialAddressPostcode: 'N14'
  invalidAddressPostcode: 'Z99 9ZZ'
  emptyAddressPostcode: ''

featureToggles:
  enabled: false

govPayTestCardNos:
  validCardNo: '4242424242424242'

govPayTestCardDetails:
  expiryMonth: '06'
  expiryYear: '99'
  cardholderName: 'Test Payment'
  cvc: '123'
  addressLine1: '1'
  addressCity: 'London'
  addressPostcode: 'SW1A1AA'

validation:
  url: 'http://localhost:8081/validate'

TestGovUkConfirmPaymentUrl: 'www.payments.service.gov.uk'
TestGovUkCardPaymentsUrl: '/card_details'

s2sStubErrorSequence: '000'

pact:
  pactBrokerUrl: 'http://localhost:80'

services:
  orchestrator:
    url: ''
  payment:
    url: ''
  equalityAndDiversity:
    url: ''
